name: Parent Action 4

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Parent script
        run: echo Hello, world!

      - name: Run the Child script
        run: |
          curl -XPOST -u "${{ secrets.CHILD_ACTION_SECRET_1 }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type:application/json" \
          https://api.github.com/repos/epamemail/github_child_action/actions/workflows/child_action_4.yml/dispatches \
          --data '{"ref": "main", "inputs": { "parametr": "Custom value" }}'
          
          
          
      - name: Get the Child run number
        run: |
          run_number=$(curl -u "${{ secrets.CHILD_ACTION_SECRET_1 }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type:application/json" https://api.github.com/repos/epamemail/github_child_action/actions/workflows/child_action_4.yml/runs | jq '.workflow_runs[])
          
      - name: Echo the Child run number
        run: echo Query params ${run_number}
