name: Parent Action 2

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Parent script
        run: echo Hello, world!

      - name: Run the Child script
        run: |
          curl -XPOST -u "${{ secrets.CHILD_ACTION_SECRET_1 }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/epamemail/github_child_action/actions/workflows/child_action_2.yml/dispatches --data '{"ref": "master"}'
          
          
          
# curl -XPOST -u "${{ secrets.CHILD_ACTION_SECRET_1 }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/epamemail/github_child_action/dispatches --data '{"event_type": "ping"}'
